# 1. Start with a Python base image
FROM python:3.12-alpine

# 2. Set the working directory
WORKDIR /code

# 3. Copy the task file
COPY task.py .


# 5. Define the command to start the app
CMD ["python", "task.py"]

