# Create AWS Lambda function with inline code
AWSTemplateFormatVersion: '2010-09-09'
Resources:
  MyLambdaFunction:
    Type: 'AWS::Lambda::Function'
    Properties:
      FunctionName: 'MyInlineLambdaFunction'
      Runtime: 'python3.12'
      Role:  'arn:aws:iam::832014379019:role/lambda-basic-role'  # Replace with your IAM role ARN
      Handler: 'index.lambda_handler'
      Code:
        ZipFile: |
          import json
          def lambda_handler(event, context):
              
              print("Received event:", json.dumps(event))

              name = event.get("name", "Unknown")
              age = event.get("age", "Not provided")
              country = event.get("country", "Not provided")

              response = {
                  "message": "User data received successfully",
                  "input_received": {
                      "name": name,
                      "age": age,
                      "country": country
                  }
              }

              return {
                  "statusCode": 200,
                  "body": response
              }