AWSTemplateFormatVersion: '2010-09-09'

Resources:
  MyLambdaFunction:
    Type: 'AWS::Lambda::Function'
    Properties:
      FunctionName: 'MyContainerLambdaFunction'
      PackageType: Image
      Role: 'arn:aws:iam::832014379019:role/lambda-basic-role'

      Code:
        ImageUri: '832014379019.dkr.ecr.us-east-1.amazonaws.com/lambda-container:v1'